Make fypp install/export optional
ecmwf/fckit pull request #35
Opened 2024-02-23 16:14 UTC by awnawab

Currently, fckit will override any local fypp if it is included in a bundle. This can be problematic if a project in that bundle needs a newer version of fypp. This PR changes the default behaviour so that fypp is only installed and exported by fckit if it is not already found.
Could you please tag a release once this PR is approved and merged? I would like to include it in an updated ifs-bundle.

2024-02-23 16:14 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/fckit?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/fckit?pullRequest=35) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/fckit?pullRequest=35) it.</sub>

2024-02-24 19:56 UTC, wdeconinck commented
This currently fails the downstream-ci:  
```
/usr/bin/python3.9: can't open file '/opt/actions-runner/work/_work/_temp/install/fckit/libexec/fckit-fypp.py': 
[Errno 2] No such file or directory
```

2024-02-24 21:43 UTC, wdeconinck requested changes

2024-02-24 21:43 UTC, wdeconinck commented on CMakeLists.txt
> +endif()
We need to (re)install the externally found fypp as well, so that downstream packages using fckit's macro can use it as well.

2024-02-27 10:52 UTC, merged

2024-02-27 11:07 UTC, wdeconinck commented
@awnawab version 0.11.1 contains this change.